### ISSUE TITLE
Branch session not initialized on app resume

### ISSUE THREAD

**Issue by sean-hill** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#263] opened 2016-01-05 19:20 UTC
Hey there,

In my Cordova based app, if you close the app and reopen it again, and try to go call something like `branch.link` it returns `undefined` and an error saying branch is not initialized. I had successfully initialized branch when the app started, but when the app resumes it appears to lose the initialization.

**Comment by aaustin** [comment] 2016-01-06 04:26
Hey Sean - I think it might be that the instructions for adding Cordova were incorrect on the repo. Can you try adding it as instructed here: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK?

This repository is just the plain web SDK for websites, so it doesn't do the required session tracking that Cordova needs.

**Comment by sean-hill** [comment] 2016-01-06 14:05
@aaustin sure thing. Is there a specific part that you think I could have implemented wrong by following the web SDK instructions?

**Comment by aaustin** [comment] 2016-01-06 15:10
Ah yes - the web SDK repo is missing code to handle the `open`/`close` cycle needed for lifecycle management of a normal app. In the website world, we just call `open` once on page load but never close. This is because we felt that website visits didn't have the same sort of deep linking requirements that apps do. If the session is never closed out, it won't retrieve new parameters.

**Comment by sean-hill** [comment] 2016-01-06 15:26
@aaustin I'm using the Cordova Plugin as you pointed to above in my already, from that repo it says "The session close will be sent automatically on any ‘pause’ event.". I assume that should be happening for me automatically. I'm using version 1.7.0 of the repo.

**Comment by aaustin** [comment] 2016-01-06 21:53
Oh oh - I'm sorry. I misread your initial issue. I bet it's because you're not calling init in the correct place so it's not triggering again when you reopen the app. Can you take a gander at the lifecycle stuff in the testbed?

https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/cordova-testbed/www/js/index.js#L38

**Comment by sean-hill** [comment] 2016-01-06 22:43
@aaustin sure thing, do I need to call `branch.close()` myself? I thought the SDK took care of that. It looks like the issue I might be having is that I'm not calling `branch.init()` again on app resume.

**Comment by aaustin** [comment] 2016-01-07 06:52
It looks like you don't. Especially given that the sessions closed out and didn't reopen when you reopened the app. Yea. Per your description, I'd also guess that the issue is not calling init on app resume. Did you try it yet?

**Comment by aaustin** [comment] 2016-01-07 06:52
Going to close this out of web SDK.

**Closed by aaustin** 2016-01-07 06:52 UTC
