### ISSUE TITLE
Clicking a link created after init after clicking a link resolves old data

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#240] opened 2015-11-18 23:10 UTC
- Click a deeplink (**A**) on the web
- You'll be redirected
- `branch.init`
- Get data of **A**
- `branch.link` (B)
- Click the created link **B**
- You'll be redirected
- `branch.init`
- Get data of ... **A** (expected **B**)

Refresh keeping the `?_branch_match_id=XXX` keeps resolving **A**
- Remove `?_branch_match_id=XXX` and press enter
- `branch.init`
- Get data of **B**

**Comment by derrickstaten** [comment] 2015-11-29 19:31
Thanks for filing this. We have a task internally to fix this.

**Comment by SleeplessByte** [comment] 2015-12-01 09:28
:+1:

**Comment by sweetlikepete** [comment] 2015-12-01 13:57
I've tracked down what I think is the issue. When the SDK is deciding to cache or refetch init data there is a check which is resolving to true when (presumably) it should not. 

[link_identifier === sessionData['click_id']](https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/tree/master/src/6_branch.js#L464)

sessionData['click_id'] is the cached identifier of the last visited link - that part is correct.
link_identifier gets initialized from the 'r' hash, i.e. http://127.0.0.1:5000/linkage-c/#r:172663601188894407 

The problem seems to be all links created through branch.link (that look like https://bnc.lt/l/95Kcs0EAY7) redirect to different urls, but with the hash.

The reason  ```?_branch_match_id=XXX``` resolves the issue is because it trumps the value of the 'r' hash.

[(utils.getParamValue('_branch_match_id') || utils.hashValue('r'))](https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/tree/master/src/6_branch.js#L375)

My conclusion is that the error lives in the redirect logic on bnc.lt. It should generate a unique hash per url.

**Comment by aaustin** [comment] 2015-12-01 18:01
@sweetlikepete That unique identifier is our browser fingerprint or unique cookie. The way the backend works is that we register a 'click' event on the given link for a given Branch cookie. The web SDK should pass that identifier (cookie) to us and we'll look for the link that was just clicked, returning the data.

@SleeplessByte However, upon testing, I can't seem to replicate the issue. Maybe it's something about my setup. I have these two links that point to the demo app:
https://bnc.lt/m/K1RCFVN7oi
https://bnc.lt/m/13SSy97cfc

If I click one from my iPhone, it passes the data in. Then I click the other, and it passes that data in. However, going back to click one or the other will not deep link.

Can you confirm that it's still deep linking repeatedly when you refresh as well? I can't seem to reproduce that either.

**Comment by sweetlikepete** [comment] 2015-12-01 20:26
If the bug is that the return value from branch.data() is always the same as on any page navigated to through branch.link(), then I can confirm I can replicate that bug. Also it is resolved by removing [this line](https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/tree/master/src/6_branch.js#L464).

**Comment by SleeplessByte** [comment] 2015-12-02 12:24
@aaustin try it on desktop. If you can't reproduce it, I'll set up a repo for ya.

**Comment by aaustin** [comment] 2015-12-02 17:27
This was a good exercise. I think we've identified a few tangentially related issues that are being worked on now.

**Comment by sweetlikepete** [comment] 2015-12-03 12:33
Resolved in https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/pull/247

Can somebody double-check me on this before closing this bug.

**Comment by jsaleigh** [comment] 2016-03-03 01:09
The code has been merged and made live for a long time, closing this one out.  Thanks team!

**Closed by jsaleigh** 2016-03-03 01:09 UTC
